AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Portfolio Web Application
Resources:
  S3StaticWebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-s3staticwebapp
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-resumebucket
      AccessControl: Private
    DeletionPolicy: Retain
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: LambdaDynamoDBS3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            Resource:
              Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${VisitorCounterTable}
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            Resource:
            - Fn::Sub: ${ResumeBucket.Arn}/*
            - Fn::Sub: ${S3StaticWebAppBucket.Arn}/*
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-VisitorCounter
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: VisitorCounterFunction
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME:
            Ref: VisitorCounterTable
      Events:
        GetVisitorCount:
          Type: Api
          Properties:
            Path: /visitorcount
            Method: GET
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.VisitorCounterFunction61632ab3DepLayer
    Metadata:
      SamResourceId: VisitorCounterFunction
  ResumeDownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-ResumeDownload
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: ResumeDownloadFunction
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Environment:
        Variables:
          RESUME_BUCKET_NAME:
            Ref: ResumeBucket
      Events:
        DownloadResume:
          Type: Api
          Properties:
            Path: /resume/download
            Method: GET
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.ResumeDownloadFunction2d5cffd1DepLayer
    Metadata:
      SamResourceId: ResumeDownloadFunction
  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-VisitorCounterTable
      AttributeDefinitions:
      - AttributeName: visitorId
        AttributeType: S
      KeySchema:
      - AttributeName: visitorId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ResumeWebAppAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-ResumeWebAppAPI
      StageName: Prod
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Resume WebApp API
          version: 1.0
        paths:
          /visitorcount:
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VisitorCounterFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
          /resume/download:
            get:
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumeDownloadFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
  VisitorCounterApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: VisitorCounterFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ResumeWebAppAPI}/*/GET/visitorcount
  ResumeDownloadApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ResumeDownloadFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ResumeWebAppAPI}/*/GET/resume/download
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /mnt/c/prafuls-data/devops-work/prafuls-portfolio-webapp/prafuls-webapp/.aws-sam/auto-dependency-layer/adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  StaticSiteURL:
    Description: URL of the static website hosted in S3
    Value:
      Fn::GetAtt:
      - S3StaticWebAppBucket
      - WebsiteURL
  ResumeBucketArn:
    Description: ARN of the Resume S3 bucket
    Value:
      Fn::GetAtt:
      - ResumeBucket
      - Arn
  VisitorCounterApiURL:
    Description: Visitor Counter API endpoint
    Value:
      Fn::Sub: https://${ResumeWebAppAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitorcount
  ResumeDownloadApiURL:
    Description: Resume Download API endpoint
    Value:
      Fn::Sub: https://${ResumeWebAppAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/resume/download
